/*
 * --MODIFICAITON TEMPLATE --
 * This template is used to modify custom tables in BI Databases ONLY.
 * 
 * DATABASES ALLOWED:
 *-------------------------------------------------
 * [ACUREPORTS\ACUREPORTS].BusinessIntelligence
 * [ACUREPORTS\ACUREPORTS].BusinessIntelligenceDev
 * [ACUREPORTS\ACUREPORTS].Efficiency
 * [ACUREPORTS\ACUREPORTS].EfficiencyDev
 * [ACARCUSVR01].ACUBI
 * [ACARCUSVR01].ACUBI_Dev
 * [DEVWEBSQLSVR01].CUBI_Dev
 *-------------------------------------------------
 *
 * keyword: 'UPDATE' only affects entries that ALREADY EXIST
 * in the table, to enter more columns use keyword: 'ALTER TABLE'
 * ADD 'ColumnName' 'type' (ALTER COLUMN can be used too).
 * To insert more entries use keyword(s): INSERT INTO
 */ 

-- SPECIFY DATABASE
USE [ACUBI]
GO

BEGIN TRY
BEGIN TRANSACTION OPERATION -- LOCK TABLE FOR MODIFICATIONS; Increments @@TRANCOUNT

/*WRITE A TEST QUERY FIRST TO SEE THE CHANGES, THEN SPECIFY THE ROWS AFFECTED*/
DECLARE @ExpectedRowsAffected INT = 0
DECLARE @ExpectedServer AS VARCHAR(25) = ''
DECLARE @ExpectedDatabase AS VARCHAR(25) = ''

	--UPDATE /*TABLE YOU WISH TO UPDATE*/
	--SET /*FULLY QUALIFIED COLUMN YOU WISH TO UPDATE*/ = /*DESIRED VALUE*/
	--FROM /*TABLE YOU WISH TO UPDATE*/ JOIN /*TABLE WHERE DESIRED DATA IS LOCATED*/
	--	ON /*JOIN CONDITION*/
	--/*THE REST USES STANDARD QUERY SYNTAX(WHERE, GROUP BY, HAVING)*/



	--ALTER /*TABLE YOU WISH TO ALTER*/ /*MODIFICATION ADD, ALTER*/

	--INSERT INTO /*TABLE YOU WISH TO INSERT*/ VALUES (/*...*/)
	--SET IDENTITY_INSERT /*FOR TABLE PRIMARY KEYS*/ [ON | OFF]

	--SELECT * --DELETE
	--FROM /*TABLE YOU WISH TO DELETE ROWS FROM*/
	--WHERE /*ROW IDENTIFIER*/

	-- UNDO MODIFICATIONS UPON UNVERIFIED NUMBER OF ROWS ARE AFFECTED
	IF @@ROWCOUNT <> @ExpectedRowsAffected OR @@SERVERNAME <> @ExpectedServer OR DB_NAME() <> @ExpectedDatabase
		BEGIN 
			PRINT N'EXPECTATION MISMATCH; TRANSACTION ROLLEDBACK'
			PRINT CONCAT('ROWS AFFECTED : ',@ExpectedRowsAffected, ' - ',@@ROWCOUNT)
			PRINT CONCAT('SERVERS : ', @ExpectedServer, ' - ',@@SERVERNAME)
			PRINT CONCAT('DATABASES : ', @ExpectedDatabase, ' - ',DB_NAME())
			ROLLBACK TRANSACTION OPERATION
		END

	-- UNLOCK TABLE UPON SUCCESSFUL MODIFICATION
	ELSE 
		BEGIN
			PRINT 'CHANGE ACKNOWLEDGED; TRANSACTION COMMITTED'
			COMMIT TRANSACTION OPERATION
		END
END TRY

-- CATCH ERRORS
BEGIN CATCH
	-- UNDO MODIFICATIONS UPON UNSUCCESSFUL OPERATION, Also unlocks table
	IF @@TRANCOUNT > 0 BEGIN ROLLBACK TRANSACTION OPERATION END

	-- DISPLAY ERROR MESSAGE
	DECLARE @ErrMessage NVARCHAR(1000) = ERROR_MESSAGE()
	DECLARE @ErrSeverity INT = ERROR_SEVERITY() --16
	DECLARE @ErrState INT = ERROR_STATE() --1
	RAISERROR (@ErrMessage, @ErrSeverity, @ErrState)
END CATCH